version: '3.8'

networks:
  backend:
    driver: bridge
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            - MYSQL_DBHOST=db
            - MYSQL_USER=default
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
        networks:
            - backend